### ISSUE TITLE
shape[:2] Problem

### ISSUE THREAD

**Issue by ghost** [cheind/py-style-transfer#1]
I was testing the implementation with an anaconda setup on windows and it worked fine. Now on a linux server with virtualenv, it gives me an error for the shape[:2] command. It seems to be from numpy and I tried different versions of it, no success. 

Traceback (most recent call last):
  File "MyMerge.py", line 34, in <module>
    a = style.image.open('./etc/' + imageName).scale_long_to(img_scale)
  File "/path/PyStyle/style/image.py", line 202, in scale_long_to
    return self._scale_side_to(np.argmax, size, resample)
  File "/path/PyStyle/style/image.py", line 210, in _scale_side_to
    hw = self.data.shape[:2]
AttributeError: 'buffer' object has no attribute 'shape'

Not sure what else I can try. I didnt change the code, so I bet I have some incompatible versions of some packages.

**Comment by cheind** [comment]
Yes I also think that there is some incompatibility in versions. Best thing to try would be to setup a new anaconda virtual environment, install packages there, run py-styletransfer and once you have it working export the environment and re-create on linux.

**Comment by ghost** [comment]
> Yes I also think that there is some incompatibility in versions. Best thing to try would be to setup a new anaconda virtual environment, install packages there, run py-styletransfer and once you have it working export the environment and re-create on linux.

Sounds obvious. At first I thought it would be a useless complication, but I guess its my best shot now.
