### ISSUE TITLE
Shapes do not match

### ISSUE THREAD

**Issue by victorca25** [cheind/py-style-transfer#2]
When using "generate_multiscale", for some content images it fails with errors similar to:

> RuntimeError: input and target shapes do not match: input [1 x 128 x 128 x 97], target [1 x 128 x 128 x 96] at c:\programdata\miniconda3\conda-bld\pytorch_1532500470552\work\aten\src\thcunn\generic/MSECriterion.cu:12

The same image works fine with "generate", and apparently also for the first step of generate_multiscale, but crashes for the second step. Any suggestions?

**Comment by cheind** [comment]
Yes so I think this happens because of the input size of your images. If the input size is not divisible by 2 for n-times (levels), some multiscale levels might generate odd dimensions. Could you retry with a resized image?

**Comment by victorca25** [comment]
That was exactly it! Thanks!

**Comment by cheind** [comment]
welcome!
